AWSTemplateFormatVersion: '2010-09-09'
Description: Dynamo

Parameters:
  ProjectId:
    Type: "String"
    Description: Project Id
    Default: "projectid"

Resources:
  accountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectId}_accounts
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  accountsTableArn:
    Description: The name of the DynamoDB Table
    Value: !GetAtt accountsTable.Arn
    Export:
      Name: !Sub "${ProjectId}-dynamo-stack-table-arn"
